---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: communicator-dev
  name: servers
  labels:
    account: servers

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: communicator-dev
  name: servers
  labels:
    purpose: dev
    app: servers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servers

  template:
    metadata:
      labels:
        app: servers

    spec:
      serviceAccountName: servers
      containers:
        - name: servers
          image: servers
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  namespace: communicator-dev
  name: servers
  labels:
    app: servers
    service: servers
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: servers

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: servers
  namespace: communicator-dev
  annotations:
    konghq.com/plugins: communicator-dev-cors, jwt
    konghq.com/strip-path: "true"
    konghq.com/preserve-host: "false"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /servers
            pathType: ImplementationSpecific
            backend:
              service:
                name: servers
                port:
                  number: 4000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: communicator-dev
  name: servers
spec:
  hosts:
    - servers
  http:
    - route:
        - destination:
            host: servers
      retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: connect-failure,refused-stream,503
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  namespace: communicator-dev
  name: servers
spec:
  host: servers
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-path-from-outside
  namespace: communicator-dev
spec:
  selector:
    matchLabels:
      app: servers
  action: DENY
  rules:
    - from:
        - source:
            notPrincipals:
              - "cluster.local/ns/communicator-dev/sa/users"
      to:
        - operation:
            paths: ["/private/channels"]
            methods: ["POST"]
    - from:
        - source:
            notPrincipals:
              - "cluster.local/ns/communicator-dev/sa/channels"
      to:
        - operation:
            paths: ["/private/channels/*"]
            methods: ["PATCH"]
