apiVersion: apps/v1
kind: Deployment
metadata:
  name: servers
spec:
  selector:
    matchLabels:
      app: servers
  template:
    metadata:
      labels:
        app: servers
    spec:
      imagePullSecrets:
        - name: docker-registry
      serviceAccountName: servers
      containers:
        - name: servers
          image: communicator
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - name: container-port
              containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: ENV
              value: dev

          livenessProbe:
            httpGet:
              path: /healthz
              port: container-port

          readinessProbe:
            tcpSocket:
              port: container-port
            initialDelaySeconds: 10
            periodSeconds: 10
