apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: servers
  annotations:
    konghq.com/protocols: https
    konghq.com/https-redirect-status-code: "308"
    konghq.com/plugins: jwt, communicator-dev-cors
    konghq.com/strip-path: "true"
spec:
  tls:
    - hosts:
        - dev.api.communicator.kamilwronka.com
      secretName: tls
  ingressClassName: kong
  rules:
    - host: dev.api.communicator.kamilwronka.com
      http:
        paths:
          - path: /servers
            pathType: ImplementationSpecific
            backend:
              service:
                name: servers
                port:
                  number: 4000
