apiVersion: v1
kind: Service
metadata:
  name: servers
  labels:
    app: servers
    service: servers
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: servers
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: servers
  labels:
    account: servers
