apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: servers
spec:
  hosts:
    - servers
  http:
    - route:
        - destination:
            host: servers
      retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: connect-failure,refused-stream,503
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: servers
spec:
  host: servers
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
# ---
# apiVersion: security.istio.io/v1beta1
# kind: AuthorizationPolicy
# metadata:
#   name: deny-path-from-outside
# spec:
#   selector:
#     matchLabels:
#       app: servers
#   action: DENY
#   rules:
#     - from:
#         - source:
#             notNamespaces: ["communicator-dev"]
#       to:
#         - operation:
#             paths: ["/users/create/account"]
